# Python Library - NumPy 

In [3]:
import numpy as np

In [2]:
# Import numpy library if it's not already installed
# pip install numpy from terminal should get you started.

In [3]:
n = np.array([3, 6, 7])

In [4]:
n

array([3, 6, 7])

In [5]:
# we can print n. 

In [6]:
print(n)

[3 6 7]


In [7]:
# Lets create a 3D arry, matrix

In [51]:
n_2d = np.array([[1, 2, 3.9],[3.4, 5, 6.8], [4, 5, 5]])

In [52]:
print(n_3d)

[[1.  2.  3.9]
 [3.4 5.  6.8]
 [4.  5.  5. ]]


In [53]:
n_2d

array([[1. , 2. , 3.9],
       [3.4, 5. , 6.8],
       [4. , 5. , 5. ]])

In [54]:
# Get dimension

In [55]:
n_2d.ndim

2

In [39]:
# Get Shape

In [40]:
n_2d.shape

(3, 3)

In [41]:
# How much memory 
n_2d.size

9

In [42]:
n_2d.itemsize

8

In [43]:
n.itemsize

8

In [44]:
n.dtype

dtype('int64')

In [45]:
# we can specify datatype while creating array
x = np.array([5, 6, 7] , dtype='int32')

In [46]:
x

array([5, 6, 7], dtype=int32)

In [47]:
x.size

3

In [48]:
x.itemsize

4

In [49]:
#totalsize
x.size * x.itemsize

12

In [50]:
# or we can get the same using 
# Getting number of bytes
x.nbytes

12

### Access Elements of Array/Matrix

In [57]:
x = np.array([[3, 4, 5, 6, 7, 8],[1, 2, 0, 9, 7, 6]])

In [61]:
# Here is x is 6, 2 matrix. 
# Lets see if we pass more columns in second row

In [62]:
y = np.array([[3, 4, 5, 6, 7, 8],[1, 2, 0, 9, 7, 6, 8, 9]])

In [64]:
y

array([list([3, 4, 5, 6, 7, 8]), list([1, 2, 0, 9, 7, 6, 8, 9])],
      dtype=object)

In [65]:
x

array([[3, 4, 5, 6, 7, 8],
       [1, 2, 0, 9, 7, 6]])

In [66]:
# Notice the difference. 

In [67]:
x[0, 0]

3

In [68]:
y[0, 0]

IndexError: too many indices for array

In [69]:
x[4, 5]

IndexError: index 4 is out of bounds for axis 0 with size 2

In [72]:
x[1, 5]
# which is my last number of arrary/matrix

6

In [73]:
# Retreive a specific row
x[1, :]

array([1, 2, 0, 9, 7, 6])

In [75]:
# Retrieve a specific column 
x[:, 1]

array([4, 2])

In [79]:
# Here we can apply logic of string indexing/slicing
# string[start:end:step]
# array[row, start:end:step]

In [78]:
x[0, 1:6:2]

array([4, 6, 8])

In [80]:
x

array([[3, 4, 5, 6, 7, 8],
       [1, 2, 0, 9, 7, 6]])

In [81]:
# we can change any element in arry if we want to 
x[1, 5] = 15

In [83]:
x
# Notice last element in second row last 6th column is updated to 15

array([[ 3,  4,  5,  6,  7,  8],
       [ 1,  2,  0,  9,  7, 15]])

In [86]:
# Lets say we want to update specific column 
x[:, 3]=14

# This is going to update all values of that particular column

In [87]:
x

array([[ 3,  4,  5, 14,  7,  8],
       [ 1,  2,  0, 14,  7, 15]])

In [90]:
x[:, 3] = [12, 15]
# This is going to update provided values w.r.t to thier position.

In [91]:
x

array([[ 3,  4,  5, 12,  7,  8],
       [ 1,  2,  0, 15,  7, 15]])

### Working with 3D array

In [4]:
n_3d = np.array([[[2, 3, 4], [5, 6, 7]], [[7, 8, 9], [6, 5, 4]]])

In [5]:
# create 2 sets of 2D array and group them in size []
n_3d

array([[[2, 3, 4],
        [5, 6, 7]],

       [[7, 8, 9],
        [6, 5, 4]]])

In [96]:
# Now we can use indexing and slicing in the same way 
# as we did for 2D array

In [6]:
n_3d[1, 0, 2]

9

In [7]:
n_3d[:,:, :]

array([[[2, 3, 4],
        [5, 6, 7]],

       [[7, 8, 9],
        [6, 5, 4]]])

In [8]:
n_3d[1, :, 1]

array([8, 5])

In [9]:
n_3d[0, 1, :]

array([5, 6, 7])

In [10]:
# so it works in the same way as it does for 2D array
n_3d[0, 1, 1:3:1]

array([6, 7])

In [11]:
n_3d[0, : , 1:3:1]

array([[3, 4],
       [6, 7]])

In [12]:
# Lets try to replace vlaues
n_3d[0, :, 1:3:1]= [[12, 12],[18, 18]]

In [13]:
n_3d

array([[[ 2, 12, 12],
        [ 5, 18, 18]],

       [[ 7,  8,  9],
        [ 6,  5,  4]]])

In [14]:
# It updates if we provide proper values as required by index
# it should not be less or more
# Let's see couple of examples

In [15]:
n_3d[0, :, 1:3:1]= [[12, 12, 12],[18, 18]]

ValueError: setting an array element with a sequence.

In [16]:
n_3d[0, :, 1:3:1]= [[12],[18, 18]]

ValueError: setting an array element with a sequence.

In [20]:
n_3d[0, 1]

array([ 5, 18, 18])

In [21]:
# Replace
n_3d[0, 1, 1] = 10

In [22]:
n_3d

array([[[ 2, 12, 12],
        [ 5, 10, 18]],

       [[ 7,  8,  9],
        [ 6,  5,  4]]])

In [23]:
n_3d[:, 1: 2] = 13

In [24]:
n_3d

array([[[ 2, 12, 12],
        [13, 13, 13]],

       [[ 7,  8,  9],
        [13, 13, 13]]])

### Initializing different types of Array. 

In [27]:
# Allo zero matrix
A = np.zeros((5, 2))

In [28]:
A

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
B = np.zeros((2, 2, 2), float)

In [30]:
B

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [31]:
C = np.ones((2, 2), 'int32') #  or C = np.ones((2, 2), dtype='int32')

In [32]:
C

array([[1, 1],
       [1, 1]], dtype=int32)

In [42]:
# Any other number
D = np.full((2, 2), 99, dtype = 'float')   # dtype='Float' gives error

In [43]:
D

array([[99., 99.],
       [99., 99.]])

In [45]:
# Any other matrix full_like
E = np.full_like(B, 4)

In [46]:
E

array([[[4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.]]])

In [48]:
# This also works and similar to full_like 
F = np.full(B.shape, 4)

In [49]:
F

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [50]:
# random decimal number

In [53]:
np.random.rand(4, 2)

array([[0.3563712 , 0.28932499],
       [0.93595077, 0.45629899],
       [0.36572988, 0.21832713],
       [0.18607539, 0.30415792]])

In [54]:
# we can directly give shape as it doesn't require any other parameter. 

In [58]:
# Random array of any shape
np.random.random_sample(C.shape)

array([[0.92982792, 0.3166819 ],
       [0.84485214, 0.9558209 ]])

In [61]:
# Random integer values
np.random.randint(5, 17, size=(3,3))

array([[12, 10, 12],
       [13, 14, 13],
       [13,  6, 13]])

In [62]:
np.random.randint(5, size=(3,3))

array([[0, 0, 3],
       [4, 2, 2],
       [2, 1, 3]])

In [63]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
# Repeat array

In [65]:
arr = np.array([1, 2, 3])

In [66]:
arr

array([1, 2, 3])

In [67]:
r1 = np.repeat(arr, 3)

In [68]:
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [69]:
r2 = np.repeat(arr, 3, axis = 0)

In [70]:
r2

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [80]:
r3 = np.repeat(arr, 4, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [78]:
r3

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [79]:
arr

array([1, 2, 3])

In [85]:
p = np.array([[1, 2]])

In [87]:
np.repeat(p, 2, axis=0)

array([[1, 2],
       [1, 2]])

In [88]:
np.repeat(p, 2, axis=1)

array([[1, 1, 2, 2]])

In [89]:
## Be careful when we are copying array

In [93]:
g = np.array([1, 2, 4])
h = g

In [94]:
print(g)

[1 2 4]


In [95]:
print(h)

[1 2 4]


In [98]:
g[0] = 10;

In [99]:
print(g)
print(h)

[10  2  4]
[10  2  4]


In [100]:
# Updating g has updated h as well. 
# because H is also pointing to same memory location where g is pointing. 

In [116]:
# Use copy() command
i = np.array([3, 4, 5])
j = i.copy()
j[1] = 22

In [117]:
print(i)


[3 4 5]


In [118]:
print(j)

[ 3 22  5]


### Mathematics

In [130]:
a = np.array([1, 2, 3, 4, 5])

In [121]:
print(a)

[1 2 3 4 5]


In [122]:
a + 2

array([3, 4, 5, 6, 7])

In [123]:
a -2

array([-1,  0,  1,  2,  3])

In [124]:
a*2

array([ 2,  4,  6,  8, 10])

In [125]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [131]:
a+=2
print(a)

[3 4 5 6 7]


In [132]:
a

array([3, 4, 5, 6, 7])

In [133]:
# Take another array

In [134]:
b = [2, 3, 4, 5, 6]

In [135]:
a + b

array([ 5,  7,  9, 11, 13])

In [136]:
# Take the sin of matrix
sin(a)

NameError: name 'sin' is not defined

In [137]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

In [138]:
a**2

array([ 9, 16, 25, 36, 49])

### Linear Algebra 

In [143]:
a = np.ones((3, 2))
print(a)

b = np.full((2, 3), 2)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2]
 [2 2 2]]


In [144]:
# Now we want to multiply these two matrix

In [145]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [146]:
np.matmul(a,b)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [148]:
# Now let's change dimension of one of matrix
c = np.ones((3, 3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [149]:
np.matmul(a, c)
# See it gives operand mismatch error

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [151]:
# lets do some of linear algebra stuff to find determinant
np.linalg.det(c)

0.0

In [153]:
d = np.identity(3)
print(d)
np.linalg.det(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [169]:
# Find inverse of Matrix
e = np.matrix('1, 2; 4, 5')
print(e)
np.linalg.inv(e)

[[1 2]
 [4 5]]


matrix([[-1.66666667,  0.66666667],
        [ 1.33333333, -0.33333333]])

In [177]:
f = np.array([[10, 11, 12],[13, 14, 15]])
print(f)
# f3 = np.array([[10 11 12][13 14 15]])   doesn't work
f1= np.matrix('10, 11, 12; 13, 14, 15')
print(f1)
f2= np.matrix('10 11 12; 13 14 15')
print(f2)

[[10 11 12]
 [13 14 15]]
[[10 11 12]
 [13 14 15]]
[[10 11 12]
 [13 14 15]]


### Statistics in Numpy

In [179]:
stats = np.array([[2, 3, 4],[5, 6, 7]])
stats

array([[2, 3, 4],
       [5, 6, 7]])

In [182]:
np.min(stats, axis=1)

array([2, 5])

In [186]:
np.min(stats)

2

In [187]:
np.max(stats)

7

In [188]:
np.sum(stats)

27

In [189]:
np.sum(stats, axis=0)

array([ 7,  9, 11])

In [190]:
np.sum(stats, axis=1)

array([ 9, 18])

### Reorganizing Arrays

In [192]:
before = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [199]:
print('Now print 8*1')
after = before.reshape(8, 1)
print(after)
print('Now print 4*2')
after1= before.reshape(4, 2)
print(after1)
print('Now print 2D')
after2 = before.reshape(2, 2, 2)
print(after2)
print('Mismatch between before and after dimension')
after3 = before.reshape(2, 3)
print(after3)

Now print 8*1
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Now print 4*2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Now print 2D
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Mismatch between before and after dimension


ValueError: cannot reshape array of size 8 into shape (2,3)

In [202]:
## vertically stacking matrix
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [206]:
## vertically stacking matrix
h1 = np.array([[1, 2], [3, 4]])
h2 = np.array([[5, 6], [7, 8]])

np.hstack((h1, h2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Miscellaneous 

#### Load Data from File

In [211]:
filedata = np.genfromtxt('data.txt',delimiter=',')
print(filedata)

[[ 1.  2.  3.  4.  5.  6.  6.  7.  8.]
 [23.  4.  3.  5. 46.  5. 65. 76. 75.]
 [32.  5.  4. 35. 56. 57. 65. 34. 43.]]


In [213]:
# automatically did it in float
# I can change in format I want
filedata.astype('int32')

array([[ 1,  2,  3,  4,  5,  6,  6,  7,  8],
       [23,  4,  3,  5, 46,  5, 65, 76, 75],
       [32,  5,  4, 35, 56, 57, 65, 34, 43]], dtype=int32)

In [214]:
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  6.,  7.,  8.],
       [23.,  4.,  3.,  5., 46.,  5., 65., 76., 75.],
       [32.,  5.,  4., 35., 56., 57., 65., 34., 43.]])

In [216]:
# so it again float because it pointing to same memory
filedata = filedata.astype('int32')
print(filedata)

[[ 1  2  3  4  5  6  6  7  8]
 [23  4  3  5 46  5 65 76 75]
 [32  5  4 35 56 57 65 34 43]]


#### Advanced Indexing and boolean masking 

In [218]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True],
       [False, False, False, False,  True,  True,  True, False, False]])

In [219]:
# whereever its greater than 50 return True otherwise False. 

In [222]:
filedata[filedata > 50]

array([65, 76, 75, 56, 57, 65], dtype=int32)

In [225]:
## you can index with a list in Numpy
a = np.array([1,2,3, 4, 5, 6, 7, 8, 9,])
print(a)
a[[1, 4, 7]]

[1 2 3 4 5 6 7 8 9]


array([2, 5, 8])

In [226]:
np.any(filedata>30, axis=0)

array([ True, False, False,  True,  True,  True,  True,  True,  True])

In [227]:
np.any(filedata>30, axis=1)

array([False,  True,  True])

In [229]:
np.all(filedata>7, axis=0)
# only last column

array([False, False, False, False, False, False, False, False,  True])

In [230]:
((filedata> 50) & (filedata<100))

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True],
       [False, False, False, False,  True,  True,  True, False, False]])

In [231]:
~((filedata> 50) & (filedata<100))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True, False, False, False,  True,  True]])

## Quiz

In [234]:
quizdata = np.genfromtxt('quiz.txt', delimiter=',', dtype='int32')
print(quizdata)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


### Frist Question

In [236]:
# Index element from 3 row to 4 and 1 to 2 column i.e. Index 11, 12, 16, 17

In [238]:
quizdata[2:4, 0:2]

array([[11, 12],
       [16, 17]], dtype=int32)

### Second Question

In [ ]:
# Index element that are in slanted line 2, 8, 14 20

In [244]:
quizdata[(0, 1 ,2, 3),(1, 2, 3, 4)]

array([ 2,  8, 14, 20], dtype=int32)

### Third Question

In [246]:
# Index element in first row last and second last column. 
# Then similar column from last and second last row.
# i.e. 4 5 then 24 25 29 30

In [266]:
h1 = quizdata[0:1,3:5]
print(h1)
h2 = quizdata[4:6,3:5]
print(h2)
np.vstack([h1,h2]).reshape(1,6)

[[4 5]]
[[24 25]
 [29 30]]


array([[ 4,  5, 24, 25, 29, 30]], dtype=int32)

In [269]:
# simple apprach will be 
quizdata[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int32)